# {{ managed_message }}
---
name: "Docs Check"
on:
  push:
    branches-ignore:
      - 'repo-helper-update'
      - 'pre-commit-ci-update-config'
      - 'imgbot'
  pull_request:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"
{% if enable_tests %}
      - name: Check for changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: "json"
          filters: |
            code:
              - '!{{ tests_dir }}/**'
{% endif %}
      - name: Install and Build 🔧
        uses: sphinx-toolbox/sphinx-action@sphinx-3.3.1
        {% if enable_tests %}if: steps.changes.outputs.code == 'true'{% endif %}
        with:
          pre-build-command: python -m pip install tox
          docs-folder: "{{ docs_dir }}/"
          build-command: "{{ build_command }}"
