# {{ managed_message }}
---
name: "Docs Check"
on:
  - push

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v1"
{% if enable_tests %}
      - name: Check for changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: "json"
          filters: |
            code:
              - '!{{ tests_dir }}/**'
{% endif %}
      - name: Install and Build 🔧
        uses: ammaraskar/sphinx-action@master
        {% if enable_tests %}if: steps.changes.outputs.code == 'true'{% endif %}
        with:
          pre-build-command: apt-get update && apt-get install gcc python3-dev git pandoc -y && python -m pip install tox
          docs-folder: "{{ docs_dir }}/"
          build-command: "{{ build_command }}"
