# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Flake8

on:
  push:
    paths-ignore:
      - '{{ docs_dir }}/**'
      - 'CONTRIBUTING.rst'
      - '.bumpversion.cfg'
      - '.imgbotconfig'
      - '.pre-commit-config.yaml'
      - '.pylintrc'
      - '.readthedocs.yml'
      - '.style.yapf'
      - 'stubs.txt'

jobs:
  Run:
    name: "Flake8"
    runs-on: "ubuntu-18.04"

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "{{ python_deploy_version }}"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox

      - name: "Run Flake8"
        run: "python -m tox -e lint -- --format github"
