# {{ managed_message }}
---
name: Conda Tests

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  tests:
    name: "Conda"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade repo_helper
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda update -q conda
          $CONDA/bin/conda install conda-build=3.21.0
          {% for channel in conda_channels %}
          $CONDA/bin/conda config --add channels {{ channel }}{% endfor %}

      - name: "Build and install package"
        run: |
          CURRENT_VERSION=$(git tag | tail -n 1 | cut -c 2-)
          CURRENT_VERSION=${CURRENT_VERSION:=0.0.0}
          python -m repo_helper build --conda --out-dir conda-bld/noarch

          # This mess is only necessary because conda won't fix it themselves
          # https://github.com/conda/conda/issues/1884
          $CONDA/bin/conda index ./conda-bld || exit 1
          $CONDA/bin/conda install -c file://$(pwd)/conda-bld {{ pypi_name.lower() }}=$CURRENT_VERSION -y || exit 1

      - name: "Run Tests for Python ${{ "{{" }} matrix.python-version {{ "}}" }}"
        run: |
          rm -rf {{ import_name.replace(".", "/") }}
          $CONDA/bin/pip install -r {{ tests_dir }}/requirements.txt
          $CONDA/bin/pytest {{ tests_dir }}/
