# {{ managed_message }}
---
name: Conda Tests

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  tests:
    name: "Conda"
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env
          conda-build-version: 3.21.0

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade "{{ '" "'.join(pip_dependencies) }}"
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda update -n base conda
          {% for channel in conda_channels %}$CONDA/bin/conda config --add channels {{ channel }}
          {% endfor %}
      - name: "Build and index channel"
        run: |
          python -m whey --builder whey_conda --out-dir conda-bld/noarch
          $CONDA/bin/conda index ./conda-bld || exit 1

      - name: "Search for package"
        run: |
          $CONDA/bin/conda search -c file://$(pwd)/conda-bld {{ pypi_name.lower() }}
          $CONDA/bin/conda search -c file://$(pwd)/conda-bld --override-channels {{ pypi_name.lower() }}

      - name: "Install package"
        run: |
          $CONDA/bin/conda install -c file://$(pwd)/conda-bld {{ pypi_name.lower() }}={{ version }}=py_1 -y || exit 1
{% if enable_tests %}
      - name: "Run Tests"
        run: |
          rm -rf {{ import_name.replace(".", "/") }}
          $CONDA/bin/conda install pytest coincidence || exit 1
          pip install -r tests/requirements.txt
          pytest tests/
{% endif %}
