# {{ managed_message }}
---
name: mypy

on:
  push:
    branches-ignore:
      - 'repo-helper-update'
      - 'pre-commit-ci-update-config'
      - 'imgbot'
  pull_request:

permissions:
  contents: read

jobs:
  Run:
    name: "mypy / ${{ brace("matrix.os") }}"
    runs-on: ${{ brace("matrix.os") }}

    strategy:
      matrix:
        os: {{ platforms }}
      fail-fast: false

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v4"{% if checkout_submodules %}
        with:
          submodules: {{ checkout_submodules }}{% endif %}

      - name: Check for changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: "json"
          filters: |
            code:
              - '{{ code_file_filter }}'

      - name: Setup Python 🐍
        if: steps.changes.outputs.code == 'true'
        uses: "actions/setup-python@v5"
        with:
          python-version: "{{ python_deploy_version }}"
{{ dependencies_block }}

      - name: "Run mypy"
        if: steps.changes.outputs.code == 'true'
        run: "python -m tox -e mypy -s false"
