# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: mypy

on:
  push:
    paths-ignore:
      - '{{ docs_dir }}/**'
      - 'CONTRIBUTING.rst'
      - '.bumpversion.cfg'
      - '.imgbotconfig'
      - '.pre-commit-config.yaml'
      - '.pylintrc'
      - '.readthedocs.yml'
      - '.style.yapf'
      - 'stubs.txt'

jobs:
  Run:
    name: "mypy / ${{ brace("matrix.os") }}"
    runs-on: ${{ brace("matrix.os") }}

    strategy:
      matrix:
        os: {{ platforms }}
      fail-fast: false

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "{{ python_deploy_version }}"

{{ dependencies_block }}

      - name: "Run mypy"
        run: "python -m tox -e mypy"
