# {{ managed_message }}
---

name: "GitHub Releases"
on:
  schedule:
    - cron: 0 12 * * *

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: domdfcoding/octocheese@master
        with:
          pypi_name: "{{ pypi_name }}"
        env:
          GITHUB_TOKEN: ${{ "{{" }}secrets.GITHUB_TOKEN{{ "}}" }}
        if: startsWith(github.ref, 'refs/tags/') != true
