# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Linux Tests

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.config.python-version }}"
    runs-on: "ubuntu-18.04"
    env:
      USING_COVERAGE: '3.6,3.7,3.8,3.9,pypy3'

    strategy:
      fail-fast: False
      matrix:
        config:
          - {python-version: "3.6", testenvs: "py36,build"}
          - {python-version: "3.7", testenvs: "py37,build"}
          - {python-version: "3.8", testenvs: "py38,build"}
          - {python-version: "3.9", testenvs: "py39,build"}
          - {python-version: "pypy3", testenvs: "pypy3,build"}

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.config.python-version }}"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox virtualenv
          python -m pip install --upgrade coverage_pyver_pragma

      - name: "Run Tests for Python ${{ matrix.config.python-version }}"
        run: "python -m tox -e ${{ matrix.config.testenvs }}"


      - name: "Upload Coverage"
        uses: actions/upload-artifact@v2
        with:
          name: "coverage-${{ matrix.config.python-version }}"
          path: .coverage


  Coverage:
    needs: tests
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coveralls coverage_pyver_pragma

      - name: "Download Coverage"
        uses: actions/download-artifact@v2
        with:
          path: coverage

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: coverage

      - name: Combine Coverage
        run: |
          shopt -s globstar
          python -m coverage combine coverage/**/.coverage

      - name: "Upload Combined Coverage Artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "combined-coverage"
          path: .coverage

      - name: "Upload Combined Coverage to Coveralls"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls

  Deploy:
    needs: tests

    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox

      - name: Build distributions 📦
        run: |
          tox -e build


      - name: Upload distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
