# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Windows Tests

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.config.python-version }}"
    runs-on: "windows-2019"
    env:
      USING_COVERAGE: '3.6,3.7,3.8,3.9'

    strategy:
      fail-fast: False
      matrix:
        config:
          - {python-version: "3.6", testenvs: "py36,build"}
          - {python-version: "3.7", testenvs: "py37,build"}
          - {python-version: "3.8", testenvs: "py38,build"}
          - {python-version: "3.9", testenvs: "py39,build"}

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"

      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.config.python-version }}"

      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox virtualenv

      - name: "Run Tests for Python ${{ matrix.config.python-version }}"
        run: "python -m tox -e ${{ matrix.config.testenvs }}"
